In [23]:
#! pip3 install SQLAlchemy
#! pip3 install pymysql
#! pip3 install mysqlclient

In [24]:
import pandas as pd
import pymysql

# import pandas.io.sql as psql
# import mysql.connector as connection
# import sqlalchemy as sql
# import _mysql

In [25]:
from sqlalchemy import create_engine

connect_string = 'mysql://rk_admin:rk2admin!@localhost/ol7'
engine = create_engine("mysql+pymysql://rk_admin:rk2admin!@localhost/ol7")
from sqlalchemy import text
conn = engine.connect()
# sql_engine = sql.create_engine(connect_string)

In [26]:
insStatement = "INSERT INTO model (model_id, expiry, op_tv, op_iv, cl_tv, cl_iv) VALUES (1, date('2022-05-02'), 0, -3, 0, null)"
x = conn.execute(text(insStatement))
x

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1' for key 'model.PRIMARY'")
[SQL: INSERT INTO model (model_id, expiry, op_tv, op_iv, cl_tv, cl_iv) VALUES (1, date('2022-05-02'), 0, -3, 0, null)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [29]:
df = pd.read_sql_query("select * from model", engine)
df

   model_id      expiry  op_tv  op_iv  cl_tv cl_iv
0         1  2023-06-02    0.0   -3.0    0.0  None

In [48]:
p_model_id = "1"

print("matching CALL options by expiration date for " + p_model_id)

stmt = "select ol.expiry, count(distinct ol.con_id) Options, count(*) TotalQuotes " + \
        " from model m, option_list ol, option_quote oq " + \
        " where m.expiry = ol.expiry and ol.con_id = oq.con_id " + \
        " and m.model_id = "+ p_model_id +" and ol.option_type = 'C' " + \
        "group by ol.expiry"
df = pd.read_sql_query(stmt, engine)
df

matching CALL options by expiration date for 1

       expiry  Options  TotalQuotes
0  2023-06-02        8        60710

In [50]:
print("matching CALL options by expiration date AND OPEN TV/IV " + p_model_id)

stmt = " select count(oq.id) from option_quote oq, option_list ol, stock_quote sq, model m " + \
" where oq.con_id = ol.con_id  and ol.expiry=m.expiry " + \
" and oq.id not in (select oq.id from model_run r where r.model_id = " +  p_model_id + " )" + \
" and oq.quote_date = sq.quote_date" + \
" and option_type = 'C'" + \
" and oq.open_tv >= ifnull(m.op_tv, oq.open_tv)" + \
" and oq.iv >= ifnull(m.op_iv, oq.iv)" + \
" and m.model_id = " + p_model_id

df = pd.read_sql_query(stmt, engine)
df

matching CALL options by expiration date AND OPEN TV/IV 1

   count(oq.id)
0         27665

In [53]:
stmt = "call model_open( " + p_model_id + " )"
print (stmt + ";" )
x = conn.execute(text(stmt))
x

call model_open( 1 );

In [62]:
print("matching CALL options by expiration date AND OPEN TV/IV " + p_model_id)

stmt = \
" select m.expiry, date(quote_date) open_date, count(distinct oq.con_id) contracts, count(*) quotes , count(distinct mr.cl_oq_id) closed" + \
" from model m, model_run mr,  option_quote oq, option_list ol" + \
" where m.model_id = mr.model_id" + \
" and mr.model_id = " + p_model_id + \
" and oq.id = mr.op_oq_id" + \
" and oq.con_id = ol.con_id" + \
" group by m.expiry, date(quote_date)" + \
" order by 1,2,3"

df = pd.read_sql_query(stmt, engine)
print (df[["quotes", "closed"]].sum())
df

matching CALL options by expiration date AND OPEN TV/IV 1
quotes    27665
closed        0
dtype: int64

        expiry   open_date  contracts  quotes  closed
0   2023-06-02  2023-04-27          1     178       0
1   2023-06-02  2023-04-28          1     390       0
2   2023-06-02  2023-05-01          1     390       0
3   2023-06-02  2023-05-02          1     389       0
4   2023-06-02  2023-05-03          1     390       0
5   2023-06-02  2023-05-05          2     776       0
6   2023-06-02  2023-05-08          2     779       0
7   2023-06-02  2023-05-09          2     729       0
8   2023-06-02  2023-05-10          2     772       0
9   2023-06-02  2023-05-11          2     780       0
10  2023-06-02  2023-05-12          2     598       0
11  2023-06-02  2023-05-15          4    1339       0
12  2023-06-02  2023-05-16          4    1497       0
13  2023-06-02  2023-05-17          4    1316       0
14  2023-06-02  2023-05-18          5    1687       0
15  2023-06-02  2023-05-19          5    1950       0
16  2023-06-02  2023-05-22          5    1566       0
17  2023-06-02  2023-05-23          4    1434       0
18  2023-06-02  2023-05-24          4    1195       0
19  2023-06-02  2023-05-25          4    1540       0
20  2023-06-02  2023-05-26          5    1926       0
21  2023-06-02  2023-05-30          6    2298       0
22  2023-06-02  2023-05-31          6    2264       0
23  2023-06-02  2023-06-01          7    1482       0