# Imports & Initialize DB Engine

In [1]:
#! pip3 install SQLAlchemy
#! pip3 install pymysql
#! pip3 install mysqlclient

In [91]:
import pandas as pd
import pymysql
import datetime
# import pandas.io.sql as psql
# import mysql.connector as connection
# import sqlalchemy as sql
# import _mysql

In [111]:
from sqlalchemy import create_engine

connect_string = 'mysql://rk_admin:rk2admin!@localhost/ol7'
engine = create_engine("mysql+pymysql://rk_admin:rk2admin!@localhost/ol7?autocommit=true")
from sqlalchemy import text
conn = engine.connect()
# sql_engine = sql.create_engine(connect_string)

# Create Models / Insert into Reference Tables (MODEL & MODEL_EXP)

In [96]:
op_tv_list = ["1", "2", "2.5", "3"]
op_iv_list = ["1", "2", "2.5", "3"]
cl_list = ["0.5", "1", "1.5"]
model_id = 1

for op_tv in op_tv_list:
    for op_iv in op_iv_list:
        for cl in cl_list:
            stmt = "INSERT IGNORE INTO `model` (model_id, sample_per_hr, op_tv, op_iv, cl_tv, cl_iv) VALUES (" + str(model_id) + ", 4, " + \
                    op_tv + ", " + op_iv + ", " + cl + ", " + " null )"
            results = conn.execute(text(stmt))
            model_id += 1
            stmt = "INSERT IGNORE INTO `model` (model_id, sample_per_hr, op_tv, op_iv, cl_iv, cl_tv) VALUES (" + str(model_id) + ", 4, " + \
                    op_tv + ", " + op_iv + ", " + cl + ", " + " null )"
            results = conn.execute(text(stmt))
            model_id += 1

In [123]:
# get last n expiry days
EXPIRY_DAYS = "100"
df = pd.read_sql_query("select distinct expiry "
                       "from option_list ol, option_quote oq "
                       "where oq.con_id = ol.con_id "
                       "order by 1 desc limit " + EXPIRY_DAYS, engine)
expiry_list = df["expiry"].values
for exp in expiry_list:
    stmt = "INSERT IGNORE INTO model_exp (model_id, expiry) select model_id, " + exp.strftime("%Y%m%d") +" from model"
    # print (exp, stmt)
    results = conn.execute(text(stmt))
    # print ( model_id, ":" , results.rowcount, results.lastrowid)
print("done")

done

In [124]:
df = pd.read_sql_query("select * from model", engine)
df

    model_id  sample_per_hr  op_tv  op_iv  cl_tv  cl_iv
0          1              4    1.0    1.0    0.5    NaN
1          2              4    1.0    1.0    NaN    0.5
2          3              4    1.0    1.0    1.0    NaN
3          4              4    1.0    1.0    NaN    1.0
4          5              4    1.0    1.0    1.5    NaN
..       ...            ...    ...    ...    ...    ...
91        92              4    3.0    3.0    NaN    0.5
92        93              4    3.0    3.0    1.0    NaN
93        94              4    3.0    3.0    NaN    1.0
94        95              4    3.0    3.0    1.5    NaN
95        96              4    3.0    3.0    NaN    1.5

[96 rows x 6 columns]

In [125]:
df = pd.read_sql_query("select expiry, count(*) runs from model_exp group by expiry", engine)
df

        expiry  runs
0   2022-11-18    96
1   2022-11-25    96
2   2022-12-02    96
3   2022-12-09    96
4   2022-12-16    96
5   2022-12-23    96
6   2022-12-30    96
7   2023-01-06    96
8   2023-01-13    96
9   2023-01-20    96
10  2023-01-27    96
11  2023-02-03    96
12  2023-02-10    96
13  2023-02-17    96
14  2023-02-24    96
15  2023-03-03    96
16  2023-03-10    96
17  2023-03-17    96
18  2023-03-24    96
19  2023-03-31    96
20  2023-04-06    96
21  2023-04-14    96
22  2023-06-02    96
23  2023-06-09    96
24  2023-06-16    96
25  2023-06-23    96
26  2025-01-17    96

In [100]:
,
df = pd.read_sql_query("select model_id, count(*) runs from model_exp group by model_id", engine)
rows = df['runs'].sum()
print ("total rows = ", rows)
df

total rows =  960

    model_id  runs
0          1    10
1          2    10
2          3    10
3          4    10
4          5    10
..       ...   ...
91        92    10
92        93    10
93        94    10
94        95    10
95        96    10

[96 rows x 2 columns]

# call open_options

In [126]:
model_id = "1"
print("matching CALL options by expiration date AND OPEN TV/IV " + model_id)

stmt = '''
select m.model_id, m. op_tv, op_iv, mr.run_id,
	DATE(oq.quote_date) quote_date, "->",
    ol.con_id,
    ol.strike,
    me.expiry,
    "->",
    min(oq.id) oq_id_min,
    count(*) oq_quotes,
    "->",
    format(avg(sq.trade_average),2) sq_avg,
    format(avg(oq.trade_average),2) oq_avg,
    format(avg(close_tv),2) cl_tv, format(avg(open_tv),2) op_tv, format(avg(iv),2) op_iv
from model m, model_exp_run mr, model_exp me, option_quote oq, stock_quote sq, option_list ol
where mr.op_oq_id = oq.id
and mr.run_id = me.run_id
and m.model_id = me.model_id
and oq.con_id = ol.con_id
and oq.quote_date = sq.quote_date
and ol.expiry = date("20230616")
group by m.model_id, m. op_tv, op_iv, mr.run_id, me.expiry,
	DATE(oq.quote_date),
    ol.con_id
order by model_id, expiry desc, con_id, quote_date desc;
'''
df = pd.read_sql_query(stmt, engine)
df

matching CALL options by expiration date AND OPEN TV/IV 1

Empty DataFrame
Columns: [model_id, op_tv, op_iv, run_id, quote_date, ->, con_id, strike, expiry, ->, oq_id_min, oq_quotes, ->, sq_avg, oq_avg, cl_tv, op_tv, op_iv]
Index: []

In [127]:
df = pd.read_sql_query("select model_id from model", engine)
rows = df.shape[0]
ctr = 0
print ("Start: " , datetime.datetime.now(), " rows: ", rows)
for x in df["model_id"].values:
    stmt = "call model_open( " + str(x) + " )"
    print (datetime.datetime.now(), ' [', ctr, "of", rows, "] ", stmt)
    ctr += 1
    x = conn.execute(text(stmt))
print (datetime.datetime.now(), ':  DONE')

Start:  2023-06-12 15:56:16.473328  rows:  96
2023-06-12 15:56:16.473542  [ 0 of 96 ]  call model_open( 1 )
2023-06-12 15:56:24.483173  [ 1 of 96 ]  call model_open( 2 )
2023-06-12 15:56:33.858851  [ 2 of 96 ]  call model_open( 3 )
2023-06-12 15:56:43.172182  [ 3 of 96 ]  call model_open( 4 )
2023-06-12 15:56:52.812059  [ 4 of 96 ]  call model_open( 5 )
2023-06-12 15:57:01.941922  [ 5 of 96 ]  call model_open( 6 )
2023-06-12 15:57:11.349921  [ 6 of 96 ]  call model_open( 7 )
2023-06-12 15:57:19.663841  [ 7 of 96 ]  call model_open( 8 )
2023-06-12 15:57:27.771029  [ 8 of 96 ]  call model_open( 9 )
2023-06-12 15:57:35.804254  [ 9 of 96 ]  call model_open( 10 )
2023-06-12 15:57:43.901241  [ 10 of 96 ]  call model_open( 11 )
2023-06-12 15:57:51.944326  [ 11 of 96 ]  call model_open( 12 )
2023-06-12 15:58:00.011967  [ 12 of 96 ]  call model_open( 13 )
2023-06-12 15:58:07.911057  [ 13 of 96 ]  call model_open( 14 )
2023-06-12 15:58:15.685778  [ 14 of 96 ]  call model_open( 15 )
2023-06-12 15:58:23.547060  [ 15 of 96 ]  call model_open( 16 )
2023-06-12 15:58:31.427028  [ 16 of 96 ]  call model_open( 17 )
2023-06-12 15:58:39.322608  [ 17 of 96 ]  call model_open( 18 )
2023-06-12 15:58:47.198619  [ 18 of 96 ]  call model_open( 19 )
2023-06-12 15:58:54.826819  [ 19 of 96 ]  call model_open( 20 )
2023-06-12 15:59:02.440670  [ 20 of 96 ]  call model_open( 21 )
2023-06-12 15:59:10.310712  [ 21 of 96 ]  call model_open( 22 )
2023-06-12 15:59:17.909593  [ 22 of 96 ]  call model_open( 23 )
2023-06-12 15:59:25.487227  [ 23 of 96 ]  call model_open( 24 )
2023-06-12 15:59:33.090215  [ 24 of 96 ]  call model_open( 25 )
2023-06-12 15:59:40.749063  [ 25 of 96 ]  call model_open( 26 )
2023-06-12 15:59:48.364320  [ 26 of 96 ]  call model_open( 27 )
2023-06-12 15:59:55.961793  [ 27 of 96 ]  call model_open( 28 )
2023-06-12 16:00:03.582029  [ 28 of 96 ]  call model_open( 29 )
2023-06-12 16:00:11.192035  [ 29 of 96 ]  call model_open( 30 )
2023-06-12 16:00:18.807399  [ 30 of 96 ]  call model_open( 31 )
2023-06-12 16:00:25.948788  [ 31 of 96 ]  call model_open( 32 )
2023-06-12 16:00:33.080789  [ 32 of 96 ]  call model_open( 33 )
2023-06-12 16:00:40.262208  [ 33 of 96 ]  call model_open( 34 )
2023-06-12 16:00:47.389536  [ 34 of 96 ]  call model_open( 35 )
2023-06-12 16:00:54.537620  [ 35 of 96 ]  call model_open( 36 )
2023-06-12 16:01:01.652647  [ 36 of 96 ]  call model_open( 37 )
2023-06-12 16:01:08.496823  [ 37 of 96 ]  call model_open( 38 )
2023-06-12 16:01:15.389605  [ 38 of 96 ]  call model_open( 39 )
2023-06-12 16:01:22.237961  [ 39 of 96 ]  call model_open( 40 )
2023-06-12 16:01:29.140357  [ 40 of 96 ]  call model_open( 41 )
2023-06-12 16:01:35.982154  [ 41 of 96 ]  call model_open( 42 )
2023-06-12 16:01:42.872038  [ 42 of 96 ]  call model_open( 43 )
2023-06-12 16:01:49.495729  [ 43 of 96 ]  call model_open( 44 )
2023-06-12 16:01:56.132802  [ 44 of 96 ]  call model_open( 45 )
2023-06-12 16:02:02.753931  [ 45 of 96 ]  call model_open( 46 )
2023-06-12 16:02:09.442900  [ 46 of 96 ]  call model_open( 47 )
2023-06-12 16:02:16.154321  [ 47 of 96 ]  call model_open( 48 )
2023-06-12 16:02:22.847217  [ 48 of 96 ]  call model_open( 49 )
2023-06-12 16:02:30.042223  [ 49 of 96 ]  call model_open( 50 )
2023-06-12 16:02:37.181768  [ 50 of 96 ]  call model_open( 51 )
2023-06-12 16:02:44.346681  [ 51 of 96 ]  call model_open( 52 )
2023-06-12 16:02:51.456082  [ 52 of 96 ]  call model_open( 53 )
2023-06-12 16:02:58.582877  [ 53 of 96 ]  call model_open( 54 )
2023-06-12 16:03:05.762787  [ 54 of 96 ]  call model_open( 55 )
2023-06-12 16:03:12.457270  [ 55 of 96 ]  call model_open( 56 )
2023-06-12 16:03:19.136352  [ 56 of 96 ]  call model_open( 57 )
2023-06-12 16:03:25.795291  [ 57 of 96 ]  call model_open( 58 )
2023-06-12 16:03:32.420854  [ 58 of 96 ]  call model_open( 59 )
2023-06-12 16:03:39.121132  [ 59 of 96 ]  call model_open( 60 )
2023-06-12 16:03:46.032887  [ 60 of 96 ]  call model_open( 61 )
2023-06-12 16:03:52.440267  [ 61 of 96 ]  call model_open( 62 )
2023-06-12 16:03:58.874030  [ 62 of 96 ]  call model_open( 63 )
2023-06-12 16:04:05.318042  [ 63 of 96 ]  call model_open( 64 )
2023-06-12 16:04:11.702027  [ 64 of 96 ]  call model_open( 65 )
2023-06-12 16:04:18.096771  [ 65 of 96 ]  call model_open( 66 )
2023-06-12 16:04:24.480471  [ 66 of 96 ]  call model_open( 67 )
2023-06-12 16:04:30.658162  [ 67 of 96 ]  call model_open( 68 )
2023-06-12 16:04:36.852616  [ 68 of 96 ]  call model_open( 69 )
2023-06-12 16:04:42.983401  [ 69 of 96 ]  call model_open( 70 )
2023-06-12 16:04:49.116732  [ 70 of 96 ]  call model_open( 71 )
2023-06-12 16:04:55.270231  [ 71 of 96 ]  call model_open( 72 )
2023-06-12 16:05:01.434941  [ 72 of 96 ]  call model_open( 73 )
2023-06-12 16:05:08.070470  [ 73 of 96 ]  call model_open( 74 )
2023-06-12 16:05:14.711098  [ 74 of 96 ]  call model_open( 75 )
2023-06-12 16:05:21.337744  [ 75 of 96 ]  call model_open( 76 )
2023-06-12 16:05:27.937488  [ 76 of 96 ]  call model_open( 77 )
2023-06-12 16:05:34.531992  [ 77 of 96 ]  call model_open( 78 )
2023-06-12 16:05:41.163309  [ 78 of 96 ]  call model_open( 79 )
2023-06-12 16:05:47.290726  [ 79 of 96 ]  call model_open( 80 )
2023-06-12 16:05:53.404739  [ 80 of 96 ]  call model_open( 81 )
2023-06-12 16:05:59.520453  [ 81 of 96 ]  call model_open( 82 )
2023-06-12 16:06:05.692391  [ 82 of 96 ]  call model_open( 83 )
2023-06-12 16:06:11.877518  [ 83 of 96 ]  call model_open( 84 )
2023-06-12 16:06:18.008169  [ 84 of 96 ]  call model_open( 85 )
2023-06-12 16:06:23.966836  [ 85 of 96 ]  call model_open( 86 )
2023-06-12 16:06:29.895967  [ 86 of 96 ]  call model_open( 87 )
2023-06-12 16:06:35.842732  [ 87 of 96 ]  call model_open( 88 )
2023-06-12 16:06:41.799472  [ 88 of 96 ]  call model_open( 89 )
2023-06-12 16:06:47.725534  [ 89 of 96 ]  call model_open( 90 )
2023-06-12 16:06:53.652051  [ 90 of 96 ]  call model_open( 91 )
2023-06-12 16:06:59.357062  [ 91 of 96 ]  call model_open( 92 )
2023-06-12 16:07:05.081761  [ 92 of 96 ]  call model_open( 93 )
2023-06-12 16:07:10.812597  [ 93 of 96 ]  call model_open( 94 )
2023-06-12 16:07:16.521662  [ 94 of 96 ]  call model_open( 95 )
2023-06-12 16:07:22.210358  [ 95 of 96 ]  call model_open( 96 )
2023-06-12 16:07:27.908751 :  DONE

In [128]:
print("matching CALL options by expiration date AND OPEN TV/IV " , p_model_id)

stmt = '''
select m.model_id,  me.run_id, me.expiry, count(*) quotes
from model m, model_exp_run mr, model_exp me, option_quote oq, stock_quote sq, option_list ol
where mr.op_oq_id = oq.id
and mr.run_id = me.run_id
and m.model_id = me.model_id
and oq.con_id = ol.con_id
and oq.quote_date = sq.quote_date
-- and ol.expiry = date("20230616")
group by m.model_id, me.run_id,  me.expiry
order by me.expiry '''

df = pd.read_sql_query(stmt, engine)
print (" Total qutoes: ", df[["quotes"]].sum())
df

matching CALL options by expiration date AND OPEN TV/IV  1
 Total qutoes:  quotes    1291062
dtype: int64

      model_id  run_id      expiry  quotes
0            1    5863  2022-11-18    1727
1            2    5864  2022-11-18    1727
2            3    5865  2022-11-18    1727
3            4    5866  2022-11-18    1727
4            5    5867  2022-11-18    1727
...        ...     ...         ...     ...
2587        92    2652  2025-01-17    1217
2588        93    2653  2025-01-17    1217
2589        94    2654  2025-01-17    1217
2590        95    2655  2025-01-17    1217
2591        96    2656  2025-01-17    1217

[2592 rows x 4 columns]

In [129]:
df = pd.read_sql_query("select model_id from model", engine)
rows = df.shape[0]
ctr = 0
print ("Start: " , datetime.datetime.now(), " rows: ", rows)
for x in df["model_id"].values:
    stmt = "call model_close( " + str(x) + " )"
    print (datetime.datetime.now(), ' [', ctr, "of", rows, "] ", stmt)
    ctr += 1
    x = conn.execute(text(stmt))
print (datetime.datetime.now(), ':  DONE!')

Start:  2023-06-12 16:09:15.587769  rows:  96
2023-06-12 16:09:15.587944  [ 0 of 96 ]  call model_close( 1 )
2023-06-12 16:11:21.849052  [ 1 of 96 ]  call model_close( 2 )
2023-06-12 16:13:30.789821  [ 2 of 96 ]  call model_close( 3 )
2023-06-12 16:15:36.856473  [ 3 of 96 ]  call model_close( 4 )
2023-06-12 16:17:58.381447  [ 4 of 96 ]  call model_close( 5 )
2023-06-12 16:20:13.239855  [ 5 of 96 ]  call model_close( 6 )
2023-06-12 16:22:34.161214  [ 6 of 96 ]  call model_close( 7 )
2023-06-12 16:24:24.043511  [ 7 of 96 ]  call model_close( 8 )
2023-06-12 16:26:28.607765  [ 8 of 96 ]  call model_close( 9 )
2023-06-12 16:28:27.256539  [ 9 of 96 ]  call model_close( 10 )
2023-06-12 16:30:32.465594  [ 10 of 96 ]  call model_close( 11 )
2023-06-12 16:32:40.774464  [ 11 of 96 ]  call model_close( 12 )
2023-06-12 16:34:44.470465  [ 12 of 96 ]  call model_close( 13 )
2023-06-12 16:36:24.526169  [ 13 of 96 ]  call model_close( 14 )
2023-06-12 16:38:18.160760  [ 14 of 96 ]  call model_close( 15 )
2023-06-12 16:40:11.614679  [ 15 of 96 ]  call model_close( 16 )
2023-06-12 16:42:06.773844  [ 16 of 96 ]  call model_close( 17 )
2023-06-12 16:44:06.554833  [ 17 of 96 ]  call model_close( 18 )
2023-06-12 16:46:04.513121  [ 18 of 96 ]  call model_close( 19 )
2023-06-12 16:47:44.085339  [ 19 of 96 ]  call model_close( 20 )
2023-06-12 16:49:38.522058  [ 20 of 96 ]  call model_close( 21 )
2023-06-12 16:51:27.474255  [ 21 of 96 ]  call model_close( 22 )
2023-06-12 16:53:22.317844  [ 22 of 96 ]  call model_close( 23 )
2023-06-12 16:55:19.307891  [ 23 of 96 ]  call model_close( 24 )
2023-06-12 16:57:16.346294  [ 24 of 96 ]  call model_close( 25 )
2023-06-12 16:59:04.125925  [ 25 of 96 ]  call model_close( 26 )
2023-06-12 17:01:22.598552  [ 26 of 96 ]  call model_close( 27 )
2023-06-12 17:03:18.229935  [ 27 of 96 ]  call model_close( 28 )
2023-06-12 17:05:24.753783  [ 28 of 96 ]  call model_close( 29 )
2023-06-12 17:07:26.077956  [ 29 of 96 ]  call model_close( 30 )
2023-06-12 17:09:36.304585  [ 30 of 96 ]  call model_close( 31 )
2023-06-12 17:14:08.584869  [ 31 of 96 ]  call model_close( 32 )
2023-06-12 19:24:34.581045  [ 32 of 96 ]  call model_close( 33 )
2023-06-12 21:15:40.683502  [ 33 of 96 ]  call model_close( 34 )
2023-06-12 22:02:09.815671  [ 34 of 96 ]  call model_close( 35 )
2023-06-12 22:04:11.534605  [ 35 of 96 ]  call model_close( 36 )
2023-06-12 22:06:15.578977  [ 36 of 96 ]  call model_close( 37 )
2023-06-12 22:07:58.783140  [ 37 of 96 ]  call model_close( 38 )
2023-06-12 22:09:52.543727  [ 38 of 96 ]  call model_close( 39 )
2023-06-12 22:11:38.817876  [ 39 of 96 ]  call model_close( 40 )
2023-06-12 22:13:43.675403  [ 40 of 96 ]  call model_close( 41 )
2023-06-12 22:15:35.596558  [ 41 of 96 ]  call model_close( 42 )
2023-06-12 22:17:34.545171  [ 42 of 96 ]  call model_close( 43 )
2023-06-12 22:19:08.689386  [ 43 of 96 ]  call model_close( 44 )
2023-06-12 22:20:57.794937  [ 44 of 96 ]  call model_close( 45 )
2023-06-12 22:22:44.942291  [ 45 of 96 ]  call model_close( 46 )
2023-06-12 22:24:59.786775  [ 46 of 96 ]  call model_close( 47 )
2023-06-12 22:26:54.032367  [ 47 of 96 ]  call model_close( 48 )
2023-06-12 22:28:57.379143  [ 48 of 96 ]  call model_close( 49 )
2023-06-12 22:30:47.828892  [ 49 of 96 ]  call model_close( 50 )
2023-06-12 22:32:56.223592  [ 50 of 96 ]  call model_close( 51 )
2023-06-12 22:34:51.034016  [ 51 of 96 ]  call model_close( 52 )
2023-06-12 22:36:56.616070  [ 52 of 96 ]  call model_close( 53 )
2023-06-12 22:38:52.071024  [ 53 of 96 ]  call model_close( 54 )
2023-06-12 22:40:58.895979  [ 54 of 96 ]  call model_close( 55 )
2023-06-12 22:42:32.320920  [ 55 of 96 ]  call model_close( 56 )
2023-06-12 22:44:24.003663  [ 56 of 96 ]  call model_close( 57 )
2023-06-12 22:46:04.776712  [ 57 of 96 ]  call model_close( 58 )
2023-06-12 22:47:58.380918  [ 58 of 96 ]  call model_close( 59 )
2023-06-12 22:49:45.335123  [ 59 of 96 ]  call model_close( 60 )
2023-06-12 22:51:42.376763  [ 60 of 96 ]  call model_close( 61 )
2023-06-12 22:53:14.869219  [ 61 of 96 ]  call model_close( 62 )
2023-06-12 22:55:08.562770  [ 62 of 96 ]  call model_close( 63 )
2023-06-12 22:56:50.036664  [ 63 of 96 ]  call model_close( 64 )
2023-06-12 22:58:45.556295  [ 64 of 96 ]  call model_close( 65 )
2023-06-12 23:00:33.109683  [ 65 of 96 ]  call model_close( 66 )
2023-06-12 23:02:30.629710  [ 66 of 96 ]  call model_close( 67 )
2023-06-12 23:03:59.858375  [ 67 of 96 ]  call model_close( 68 )
2023-06-12 23:05:46.786740  [ 68 of 96 ]  call model_close( 69 )
2023-06-12 23:07:22.838031  [ 69 of 96 ]  call model_close( 70 )
2023-06-12 23:09:08.704018  [ 70 of 96 ]  call model_close( 71 )
2023-06-13 00:53:38.514388  [ 71 of 96 ]  call model_close( 72 )
2023-06-13 03:41:30.316180  [ 72 of 96 ]  call model_close( 73 )
2023-06-13 06:31:02.771466  [ 73 of 96 ]  call model_close( 74 )
2023-06-13 07:23:18.578047  [ 74 of 96 ]  call model_close( 75 )
2023-06-13 07:25:14.896236  [ 75 of 96 ]  call model_close( 76 )
2023-06-13 07:27:27.522020  [ 76 of 96 ]  call model_close( 77 )
2023-06-13 07:29:22.122915  [ 77 of 96 ]  call model_close( 78 )
2023-06-13 07:31:25.915604  [ 78 of 96 ]  call model_close( 79 )
2023-06-13 07:32:55.310183  [ 79 of 96 ]  call model_close( 80 )
2023-06-13 07:34:49.795164  [ 80 of 96 ]  call model_close( 81 )
2023-06-13 07:36:23.926127  [ 81 of 96 ]  call model_close( 82 )
2023-06-13 07:38:14.186040  [ 82 of 96 ]  call model_close( 83 )
2023-06-13 07:39:54.339972  [ 83 of 96 ]  call model_close( 84 )
2023-06-13 07:41:46.909819  [ 84 of 96 ]  call model_close( 85 )
2023-06-13 07:43:10.086481  [ 85 of 96 ]  call model_close( 86 )
2023-06-13 07:44:54.432901  [ 86 of 96 ]  call model_close( 87 )
2023-06-13 07:46:22.893854  [ 87 of 96 ]  call model_close( 88 )
2023-06-13 07:48:05.417377  [ 88 of 96 ]  call model_close( 89 )
2023-06-13 07:49:41.257539  [ 89 of 96 ]  call model_close( 90 )
2023-06-13 07:51:34.515526  [ 90 of 96 ]  call model_close( 91 )
2023-06-13 07:52:55.944750  [ 91 of 96 ]  call model_close( 92 )
2023-06-13 07:54:31.945100  [ 92 of 96 ]  call model_close( 93 )
2023-06-13 07:55:55.532568  [ 93 of 96 ]  call model_close( 94 )
2023-06-13 07:57:43.727420  [ 94 of 96 ]  call model_close( 95 )
2023-06-13 07:59:12.298915  [ 95 of 96 ]  call model_close( 96 )
2023-06-13 08:00:54.942092 :  DONE!