# Imports & Initialize DB Engine

In [1]:
#! pip3 install SQLAlchemy
#! pip3 install mysqlclient
#! pip3 install pymysql

In [3]:
import pandas as pd
import pymysql
import datetime
# import pandas.io.sql as psql
# import mysql.connector as connection
# import sqlalchemy as sql
# import _mysql

In [4]:

from sqlalchemy import create_engine

connect_string = 'mysql://rk_admin:rk2admin!@localhost/ol7'
engine = create_engine("mysql+pymysql://rk_admin:rk2admin!@localhost/ol7?autocommit=true")
from sqlalchemy import text

conn = engine.connect()
# sql_engine = sql.create_engine(connect_string)

# Get status

In [9]:
#
#  name: option_pull_status_summary.sql
#		show last 30 days
stmt = '''
select c.quote_date, c.expiry, format(avg(sq.trade_average),2) stock_quote, count(distinct ol_con_id) strikes, group_concat( distinct concat(c.strike,  ' (', c.calls, "/", p.calls, ')' ) order by c.strike) quote_counts
from
stock_quote sq
join
  (select date(quote_date) quote_date, ol.expiry, ol.strike, ol.option_type, format(count(*), 0) calls, ol.con_id ol_con_id
	from option_quote oq, option_list ol where oq.con_id = ol.con_id
	and option_type = 'C'
	group by date(quote_date), ol.expiry, ol.strike, ol.option_type, ol.con_id) c
on (c.quote_date = date(sq.quote_date))
left join
  (select date(quote_date) quote_date, ol.expiry, ol.strike, ol.option_type, format(count(*), 0) calls, ol.con_id
	from option_quote oq, option_list ol where oq.con_id = ol.con_id
	and option_type = 'P'
	group by date(quote_date), ol.expiry, ol.strike, ol.option_type, ol.con_id) p
on ( c.quote_date = p.quote_date and c.expiry = p.expiry and c.strike = p.strike)
where c.quote_date >= CURDATE() - INTERVAL 60 DAY
group by c.quote_date, c.expiry
order by 1 desc, 2'''
df = pd.read_sql_query(stmt, engine)
df.head(30)

,quote_date,expiry,stock_quote,strikes,quote_counts
0,2023-12-01,2023-12-01,190.86,12,"170.00 (390/385),175.00 (390/390),177.50 (372/..."
1,2023-12-01,2023-12-08,190.86,7,"180.00 (377/390),185.00 (390/390),187.50 (390/..."
2,2023-12-01,2023-12-15,190.86,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
3,2023-11-30,2023-12-01,188.76,12,"170.00 (386/353),172.50 (333/390),175.00 (390/..."
4,2023-11-30,2023-12-08,188.76,7,"180.00 (381/390),185.00 (390/390),187.50 (390/..."
5,2023-11-30,2023-12-15,188.76,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
6,2023-11-29,2023-12-01,189.98,12,"170.00 (390/388),172.50 (390/386),175.00 (361/..."
7,2023-11-29,2023-12-08,189.98,7,"180.00 (382/390),185.00 (389/390),187.50 (390/..."
8,2023-11-29,2023-12-15,189.98,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
9,2023-11-28,2023-12-01,190.14,12,"170.00 (383/390),172.50 (342/385),175.00 (381/..."
10,2023-11-28,2023-12-08,190.14,7,"180.00 (385/390),185.00 (388/390),187.50 (383/..."
11,2023-11-28,2023-12-15,190.14,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
12,2023-11-27,2023-12-01,189.87,12,"170.00 (388/390),172.50 (229/390),175.00 (267/..."
13,2023-11-27,2023-12-08,189.87,4,"180.00 (390/390),185.00 (390/390),190.00 (390/..."
14,2023-11-27,2023-12-15,189.87,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
15,2023-11-24,2023-11-24,189.67,13,"165.00 (149/39),170.00 (209/210),172.50 (209/1..."
16,2023-11-24,2023-12-01,189.67,12,"170.00 (208/210),172.50 (198/210),175.00 (170/..."
17,2023-11-24,2023-12-08,189.67,4,"180.00 (204/210),185.00 (210/210),190.00 (210/..."
18,2023-11-24,2023-12-15,189.67,6,"185.00 (210/210),187.50 (206/210),190.00 (210/..."
19,2023-11-22,2023-11-24,191.72,10,"170.00 (388/386),175.00 (381/390),180.00 (390/..."
20,2023-11-22,2023-12-01,191.72,12,"170.00 (381/390),172.50 (99/382),175.00 (383/3..."
21,2023-11-22,2023-12-08,191.72,4,"180.00 (348/390),185.00 (390/390),190.00 (390/..."
22,2023-11-22,2023-12-15,191.72,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
23,2023-11-21,2023-11-24,190.39,13,"165.00 (367/386),170.00 (390/387),172.50 (389/..."
24,2023-11-21,2023-12-01,190.39,11,"170.00 (373/383),175.00 (390/390),177.50 (286/..."
25,2023-11-21,2023-12-08,190.39,4,"180.00 (389/390),185.00 (390/390),190.00 (390/..."
26,2023-11-21,2023-12-15,190.39,6,"185.00 (390/390),187.50 (390/390),190.00 (390/..."
27,2023-11-20,2023-11-24,191.35,14,"165.00 (179/390),167.50 (383/390),170.00 (390/..."
28,2023-11-20,2023-12-01,191.35,12,"170.00 (372/388),172.50 (373/390),175.00 (352/..."
29,2023-11-20,2023-12-08,191.35,4,"180.00 (390/390),185.00 (389/390),190.00 (390/..."

In [10]:
def get_strike_arr(x):
    ar = x.split(",")
    return [s.split(' ')[0] for s in ar]

In [11]:
all_strikes = []
my_set = set()
all_strikes.extend ( df["quote_counts"].apply(get_strike_arr))
for row in all_strikes:
    my_set = my_set.union( {cell for cell in row})

my_set = sorted(my_set)
#for strike in my_set:
#    print(strike)

In [12]:
def get_data(row, strike):
    ret =".."
    for st2 in row[1].split(','):
        if st2.startswith(strike[0]):
            ret = st2.split(' ')[-1]
            break
        else:
            ret = "<>"
    # print('-->', row[1], '<->', strike[0], '<-', ret)
    return ret

    # print(row)
    # l = row.split(",")
    # for j in l:
    #     if j.startswith(strike):
    #         return j.split(" ")[1].translate({ord(i): None for i in '() '})

# call df apply
for st in my_set:
    df[ st ] = df[["quote_date","quote_counts"]].apply(get_data, axis=1, args=([st],))
df

,quote_date,expiry,stock_quote,strikes,quote_counts,162.50,165.00,167.50,170.00,172.50,175.00,177.50,180.00,182.50,185.00,187.50,190.00,192.50,195.00,197.50
0,2023-12-01,2023-12-01,190.86,12,"170.00 (390/385),175.00 (390/390),177.50 (372/...",<>,<>,<>,(390/385),<>,(390/390),(372/390),(390/390),(381/390),(390/390),(390/390),(390/390),(390/390),(390/390),(390/341)
1,2023-12-01,2023-12-08,190.86,7,"180.00 (377/390),185.00 (390/390),187.50 (390/...",<>,<>,<>,<>,<>,<>,<>,(377/390),<>,(390/390),(390/390),(390/390),(390/390),(390/389),(390/390)
2,2023-12-01,2023-12-15,190.86,6,"185.00 (390/390),187.50 (390/390),190.00 (390/...",<>,<>,<>,<>,<>,<>,<>,<>,<>,(390/390),(390/390),(390/390),(390/390),(390/388),(390/337)
3,2023-11-30,2023-12-01,188.76,12,"170.00 (386/353),172.50 (333/390),175.00 (390/...",<>,<>,<>,(386/353),(333/390),(390/390),(390/376),(367/390),(388/390),(390/390),(390/390),(390/390),(390/390),(390/390),(390/383)
4,2023-11-30,2023-12-08,188.76,7,"180.00 (381/390),185.00 (390/390),187.50 (390/...",<>,<>,<>,<>,<>,<>,<>,(381/390),<>,(390/390),(390/390),(390/390),(390/390),(390/390),(390/245)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2023-10-04,2023-10-13,172.88,9,"165.00 (380/390),167.50 (390/390),170.00 (390/...",<>,(380/390),(390/390),(390/390),(390/390),(390/390),(390/390),(390/389),(390/372),(390/335),<>,<>,<>,<>,<>
220,2023-10-04,2023-10-20,172.88,9,"165.00 (389/390),167.50 (390/390),170.00 (390/...",<>,(389/390),(390/390),(390/390),(390/390),(390/390),(390/385),(390/390),(390/305),(390/370),<>,<>,<>,<>,<>
221,2023-10-04,2023-10-27,172.88,5,"165.00 (388/390),170.00 (390/390),175.00 (390/...",<>,(388/390),<>,(390/390),<>,(390/390),<>,(390/369),<>,(390/377),<>,<>,<>,<>,<>
222,2023-10-04,2023-11-03,172.88,5,"165.00 (384/390),170.00 (390/390),175.00 (390/...",<>,(384/390),<>,(390/390),<>,(390/390),<>,(390/193),<>,(390/351),<>,<>,<>,<>,<>
223,2023-10-04,2023-11-10,172.88,5,"165.00 (177/382),170.00 (389/390),175.00 (388/...",<>,(177/382),<>,(389/390),<>,(388/389),<>,(373/351),<>,(390/24),<>,<>,<>,<>,<>